apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T13:46:11Z"
  name: carts-canary
  resourceVersion: "953807"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: d59be5d5-6467-11ea-b24f-42010a84013c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
